---
title: "About"
output: 
  html_document:
    toc: true
    toc_float: true

---

# Data Source

## Ratings Data

The project utilizes the data from the [Coffee Quality Institute](https://database.coffeeinstitute.org/) (the original data can be found on [James LeDoux's github](https://github.com/jldbc/coffee-quality-database)) to rate coffee based on their acidity, sweetness, aroma, altitude, and region, offering a comprehensive look at coffee. 

To make it easier to analyze the data, we named the coffee quality ratings dataset `ratings_df`. There are many variables in this dataset, and after careful consideration in relation to our project questions, we have selected the following variables for this project:

* `total_cup_points`: Total rating/points (0 - 100 scale)

* `species`: Species of coffee bean (arabica or robusta)

* `country_of_origin`: Where the bean came from

* `variety`: Variety of the beans

* `grading_date`: When the beans were graded

* `processing_method`: Method for processing

* `aroma`: Aroma grade

* `flavor`: Flavor grade

* `aftertaste`: Aftertaste grade

* `acidity`: Acidity grade

* `body`: Body grade

* `balance`: Balance grade

* `sweetness`: Sweetness grade

* `altitude_mean_meters`: Altitude mean meters



## Survey Data

In October 2023, "world champion barista" James Hoffmann and coffee company Cometeer held the [“Great American Coffee Taste Test”](https://www.youtube.com/watch?v=bMOOQfeloH0) across the United States, during which viewers were asked to fill out a survey about their demographic information, coffee-related preferences and lifestyle, as well as their tasting experience of 4 cups of coffee ordered from Cometeer. The data is available at [GitHub](https://github.com/rfordatascience/tidytuesday/tree/master/data/2024/2024-05-14), cleaned by TidyTuesday. 

**Data Dictionary**


*Demographic Information*

* `submission_id`: Participant's submission ID

* `age`: Participant's age

* `gender`: Participant's gender

* `education_level`: Participant's education level

* `ethnicity_race`: Participant's ethnicity/race

* `employment_status`: Participant's employment status

* `wfh`: Do you work from home or in person?


*Coffee-related Preferences and Lifestyle*

* `cups`: How many cups of coffee do you typically drink per day?

* `where_drink`: Where do you typically drink coffee?

* `why_drink`: Why do you drink coffee?

* `brew`: How do you brew coffee at home?

* `purchase`: On the go, where do you typically purchase coffee?

* `favorite`: What is your favorite coffee drink?

* `additions`: Do you usually add anything to your coffee?

* `dairy`: What kind of dairy do you add?

* `sweetener`: What kind of sugar or sweetener do you add?

* `style`: Before today's tasting, which of the following best described what kind of coffee you like?

* `strength`: How strong do you like your coffee?

* `roast_level`: What roast level of coffee do you prefer?

* `caffeine`: How much caffeine do you like in your coffee?

* `expertise`: How would you rate your own coffee expertise?

* `total_spend`: In total, much money do you typically spend on coffee in a month?

* `taste`: Do you like the taste of coffee?

* `most_paid`: What is the most you've ever paid for a cup of coffee?

* `most_willing`: What is the most you'd ever be willing to pay for a cup of coffee?


*Tasting Experience of 4 Cups of Coffee Ordered*

* `coffee_name`: Name of the ordered coffee (A, B, C, D)

* `bitterness`: Bitterness rating

* `acidity`: Acidity rating

* `preference`: Personal preference rating

* `prefer_ad`: Prefer coffee A or D

* `prefer_overall`: Favorite overall coffee among 4 cups



# Team Members

* Jinghan Zhao - jz3902
* Leyang Rui - lr3257
* Yifei Yu - yy3563
* Yuechu Hu - yh3822

