---
title: "Final Project"
author: "Group 43"
date: "2024-11-21"
output: github_document
---

```{r}
library(tidyverse)
library(ggplot2)
library(modelr)
library(readxl)
library(haven)
```

## Data Importing and Cleaning

```{r, warning=FALSE, message=FALSE}
ratings_df = read_csv("data/coffee_ratings.csv") %>% 
  janitor::clean_names() %>%
  select(total_cup_points, species, country_of_origin, 
         region, number_of_bags, bag_weight, grading_date, variety,
         processing_method, aroma, flavor, aftertaste, acidity, body, balance,
         uniformity, clean_cup, sweetness, cupper_points, moisture, color,
         altitude_low_meters, altitude_high_meters, altitude_mean_meters) %>%
  mutate(grading_year = str_extract(grading_date, "\\d{4}"),
         species = as.factor(species),
         variety = as.factor(variety),
         processing_method = as.factor(processing_method),
         moisture = as.factor(moisture),
         color = as.factor(color))
```

- Survey dataset

```{r, warning=FALSE, message=FALSE}
survey = read_csv("data/coffee_survey.csv") |>
  janitor::clean_names() |>
  select(-purchase_other, -favorite_specify, -additions_other, -prefer_abc, -prefer_ad, -why_drink_other, -know_source, -value_cafe, -value_equipment, -gender_specify, -ethnicity_race_specify, -number_children, -political_affiliation, -coffee_a_notes, -coffee_b_notes, -coffee_c_notes, -coffee_d_notes) |>
  drop_na(gender) |>
  mutate_if(is.character, as.factor)
  
```














