---
title: "Final Project"
author: "Group 43"
date: "2024-11-21"
output: html_document
---

```{r setup, include = FALSE}
library(tidyverse)
library(ggplot2)
library(modelr)
library(haven)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%",
  warning = FALSE,
  message = FALSE
)
```

# Data Importing and Cleaning

## Rating dataset

```{r}
ratings_df = read_csv("data/coffee_ratings.csv") %>% 
  janitor::clean_names() %>%
  select(total_cup_points, species, country_of_origin, 
         region, number_of_bags, bag_weight, grading_date, variety,
         processing_method, aroma, flavor, aftertaste, acidity, body, balance,
         uniformity, clean_cup, sweetness, cupper_points, moisture, color,
         altitude_low_meters, altitude_high_meters, altitude_mean_meters) %>%
  mutate(grading_year = str_extract(grading_date, "\\d{4}"),
         species = as.factor(species),
         variety = as.factor(variety),
         processing_method = as.factor(processing_method),
         moisture = as.factor(moisture),
         color = as.factor(color))
```

### Exploring the data


#### The Distribution of the Total Cup Points

```{r}
points_dis = ggplot(ratings_df, aes(x = total_cup_points)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color = "black") +
  coord_cartesian(xlim = c(60, NA)) +
  theme_minimal() +
  labs(title = "Total Cup Points Distribution", x = "Total Cup Points", y = "Frequency")

ggplotly(points_dis)
```


#### The Distribution of Varieties by Species


```{r}
variety_dis = ratings_df %>%
  filter(!is.na(variety)) %>%
  ggplot(aes(x = fct_rev(fct_infreq(variety)))) +
  geom_bar(fill = "skyblue") +
  facet_grid(~ species, scales = "free_x") +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 0.5, size = 8),
    strip.text = element_text(size = 10)
  ) +
  labs(
    title = "Frequency of Varieties by Species",
    x = "Variety",
    y = "Count"
  )


ggplotly(variety_dis)
```



#### The Boxplot of Variety and Total Cup Points


```{r}
ratings_df |> 
  mutate(variety = fct_reorder(variety, total_cup_points)) |> 
  plot_ly(
    y = ~total_cup_points, 
    color = ~variety, 
    type = "box", 
    colors = "viridis"
  ) %>%
  layout(
    yaxis = list(
      title = "Total Cup Points",
      range = c(60, NA) 
    ),
    xaxis = list(
      title = "Variety"
    ))
```


#### The Distribution between Total Cup Points and Altitude by Variety

```{r}
ratings_filtered <- ratings_df %>%
  filter(!is.na(total_cup_points) & !is.na(altitude_mean_meters))

top_n_varieties = 8

top_varieties <- ratings_filtered %>%
  count(variety, sort = TRUE) %>%
  top_n(top_n_varieties, n) %>%
  pull(variety)

ratings_filtered <- ratings_filtered %>%
  mutate(
    variety = ifelse(variety %in% top_varieties, as.character(variety), "Other"),
    variety = as.factor(variety),  
    text_label = str_c("Total Cup Points: ", total_cup_points, 
                       "\nMean Altitude(meters): ", altitude_mean_meters,
                       "\nVariety: ", variety)
  )

```


```{r}
plot_ly(
  data = ratings_filtered,
  x = ~total_cup_points,
  y = ~altitude_mean_meters,
  type = "scatter",
  mode = "markers",
  color = ~variety,
  text = ~text_label,
  alpha = 0.5
) %>%
  layout(
    title = "Total Cup Points vs. Mean Altitude (meters)",
    xaxis = list(title = "Total Cup Points",
      range = c(60, max(ratings_filtered$total_cup_points, na.rm = TRUE))),
    yaxis = list(title = "Altitude Mean Meters")
  )
```




#### Analyzing the origins of top coffees each year

```{r}
top_origins = 
  ratings_df |> 
  group_by(grading_year) |> 
  arrange(grading_year, desc(total_cup_points)) |> 
  slice(1)

top_origins |> 
  arrange(grading_year) |> 
  select(grading_year, country_of_origin, total_cup_points) |> 
  knitr::kable(
    col.names = c("Year", "Country of Origin", "Total Cup Points"),
    caption = "Top Coffee by Country from 2010 to 2018",
  )

top_origins |> 
  ggplot(aes(x = grading_year, y = total_cup_points, fill = country_of_origin)) +
  geom_col() +
  labs(
    title = "Top Coffee by each year by country from 2010 to 2018",
    x = "Year",
    y = "Total Cup Points",
    fill = "Country of Origin"
  ) +
  theme_minimal()
```



## Survey dataset

```{r}
survey = read_csv("data/coffee_survey.csv") |>
  janitor::clean_names() |>
  select(-purchase_other, -favorite_specify, -additions_other, -prefer_abc, -prefer_ad, 
         -why_drink_other, -know_source, -value_cafe, -value_equipment, -gender_specify, 
         -ethnicity_race_specify, -number_children, -political_affiliation, 
         -coffee_a_notes, -coffee_b_notes, -coffee_c_notes, -coffee_d_notes) |>
  drop_na(gender) |>
  mutate_if(is.character, as.factor)
```

```{r}
survey_tidy = 
  survey %>% 
  rename_with(
    ~ sub("personal_preference", "preference", .),
    .cols = ends_with("personal_preference")
  ) %>% 
  pivot_longer(
    cols = coffee_a_bitterness:coffee_d_preference,
    values_to = "score",
    names_to = c("coffee_name", "coffee_feature"),
    names_pattern = "(.*)_(.*)"
  ) %>% 
  pivot_wider(
    names_from = coffee_feature,
    values_from = score
  ) %>% 
  mutate(
    coffee_name = case_match(coffee_name,
                             "coffee_a" ~ "Coffee A",
                             "coffee_b" ~ "Coffee B",
                             "coffee_c" ~ "Coffee C",
                             "coffee_d" ~ "Coffee D"),
    coffee_name = as.factor(coffee_name)
  ) %>% 
  relocate(prefer_overall, .after = everything())
```













